# Passwords are auto-generated by AWS and only ever retrievable right
# after creation - mark sensitive so they don't print in plain CI logs
output "initial_passwords" {
  value     = { for k, v in aws_iam_user_login_profile.team : k => v.password }
  sensitive = true
}

output "access_keys" {
  value = var.create_access_keys ? {
    for k, v in aws_iam_access_key.team : k => {
      access_key_id = v.id
      secret_key    = v.secret
    }
  } : {}
  sensitive = true
}

output "usernames" {
  value = [for u in aws_iam_user.team : u.name]
}