# Runs on every pull request - checks formatting and validity.
# No AWS credentials needed, this is pure static checking.
name: Terraform Validate (PR)

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false   # let all three environments report their own result instead of failing fast, default is true(no entry)
      matrix:
        environment: [dev, test, prod]
    defaults:
      run:
        working-directory: environments/${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend, validate only)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
  
  validate-app-group:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [iam-team-users]
    defaults:
      run:
        working-directory: app_group/${{ matrix.module }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate